name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_to_main:
    name: Deploy prod hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Firebase Tools
        run: npm install firebase-tools -g

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYTESTPROJECT_0604 }}
          # run: firebase deploy --only hosting:${{ secrets.FIREBASE_HOSTING_ID }} -P ${{ secrets.FIREBASE_PROJECT_ID }}
        run: firebase deploy mytestproject-0604
